### ISSUE TITLE
Input Field Template

### ISSUE THREAD

**Issue by Manav-Ram19** [jgetzel/cse110-w21-group21#17]

**Comment by e2huynh** [comment]
Current functionality of input template
https://gph.is/g/E0Q9Rwr

![image](https://user-images.githubusercontent.com/50161923/108585627-3e744900-72fe-11eb-9548-cfe998dd5872.png)

**Comment by e2huynh** [comment]
What should the input field do if the input is really long? This is mostly for the description input field. Stop the user from typing? Grow downwards, scroll right?

**Comment by e2huynh** [comment]
![Testing](https://media.giphy.com/media/GwGnOtxEGujPs0vDUy/giphy.gif)
![image](https://user-images.githubusercontent.com/50161923/108591649-a9ce1300-731e-11eb-96b2-c5f2a15bab24.png)

Changed the inner-workings of Input component to be a div that can expand and created "max" attribute that is a character count max.
