### ISSUE TITLE
header component

### ISSUE THREAD

**Issue by s2chitni** [jgetzel/cse110-w21-group21#22]
create a header component which will be common to various pages

**Comment by e2huynh** [comment]
@StoneT2000 How would you create `pomo-buttons` in another component? I'm trying this: 
![image](https://user-images.githubusercontent.com/50161923/108640682-f9f8c280-744f-11eb-98d9-f703006db489.png)

and I'm getting this:
![image](https://user-images.githubusercontent.com/50161923/108640695-0d0b9280-7450-11eb-8481-a0842d717050.png)

the text and styles aren't loading. I've tried `.innerHTML`, `.textContent`, and `.innerText`.

For reference this is what the header originally looks like:
![image](https://user-images.githubusercontent.com/50161923/108640776-6d9acf80-7450-11eb-90eb-29965c8f0a57.png)

**Comment by e2huynh** [comment]
![image](https://user-images.githubusercontent.com/50161923/108644719-10f5df80-7465-11eb-9ca5-ea805876de69.png)
Header is 99% done, need to write tests and maybe consider using listeners for the buttons after MVP sprint

**Comment by Manav-Ram19** [comment]
![peepo_dance](https://user-images.githubusercontent.com/60715649/108664717-2cbead00-7488-11eb-8245-5b6d235f74b0.gif)

**Comment by Kevin-Klimek** [comment]
### Header and tests finalized for MVP.
![image](https://user-images.githubusercontent.com/44188620/108777477-b322cf80-7518-11eb-88c9-679ae90eddcd.png)
Future TODO:  
* Add help functionality when modal is merged
* Refactor links as onClick from buttons? Right now the buttons aren't actually using button functionality, they are
* Potentially recolor and disable the button for the current page
   ie: when on the history page, the history button is "toggled" by being recolored and unclickable
