### ISSUE TITLE
Input Security

### ISSUE THREAD

**Issue by Manav-Ram19** [jgetzel/cse110-w21-group21#55]
1. Fix "data type" of input
2. Fix max number of characters
3. Fix required or not
4. Fix default test

**Comment by e2huynh** [comment]
Current functionality:
![link](https://media.giphy.com/media/Hf3ym8Sxbdwjd5tdsB/giphy.gif)

To achieve this in the modal use this:
```
<div><pomo-input required="true" id="task-name">Enter A Task Name</pomo-input></div>
<div><pomo-input required="true" type="number" max="3" id="pomos-required">Pomos Required</pomo-input></div
<div><pomo-input max ="250" id="description">Description</pomo-input></div>
```

The inner text sets the placeholder.
`required="true"` adds the * at the end.
`type="number"` only allows for numeric inputs and the input field will shake if the user tries to type a non-number.
`max="3"` will set the max character limit to 3 characters.

**Comment by e2huynh** [comment]
Finished (see latest PR for details)
