### ISSUE TITLE
Convert Modal to be more flexible

### ISSUE THREAD

**Issue by Manav-Ram19** [jgetzel/cse110-w21-group21#56]
1. Give freedom to use modal with/without input components.
2. This way we can use it for the "help" button thing.

**Comment by e2huynh** [comment]
- Made modal more modular, can add whatever elements you want now.
- A task is no longer added if the user has not entered a task name and estimated pomos.
- Input fields are now cleared when a task is successfully added.
- If nothing was entered for "Description" the resulting task would have an "undefined" description. Now it is an empty string.

![New Modal](https://media.giphy.com/media/B7kkwsBsjtZGcfXU6w/giphy.gif)
